CREATE DATABASE DINOSSAUROS
DROP DATABASE DINOSSAUROS
CREATE TABLE GRUPOS
(
	ID INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(20) NOT NULL
)

CREATE TABLE ERAS
(
	ID INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(20) NOT NULL,
	ANO_INICIO INTEGER NOT NULL,
	ANO_FIM INTEGER NOT NULL
)

CREATE TABLE REGIOES
(
	ID INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL
)

CREATE TABLE DINOSSAUROS
(
	ID INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	TONELADAS INTEGER NOT NULL,
	ANO_DESCOBERTA INTEGER NOT NULL,
	ANO_INICIO INTEGER NOT NULL,
	ANO_FIM INTEGER NOT NULL,
	FK_ERAS INTEGER,
	FK_GRUPOS INTEGER,
	FOREIGN KEY (FK_ERAS) REFERENCES ERAS(ID),
	FOREIGN KEY (FK_GRUPOS) REFERENCES GRUPOS(ID)
)

CREATE TABLE DESCOBRIDORES
(
	ID INTEGER PRIMARY KEY IDENTITY,
	NOME VARCHAR(45) NOT NULL,
	FK_DINOSSAURO INTEGER,
	FOREIGN KEY (FK_DINOSSAURO) REFERENCES DINOSSAUROS(ID)
)

CREATE TABLE REGIAO_DINO
(
	ID INTEGER PRIMARY KEY,
	FK_DINOSSAURO INTEGER,
	FK_REGIAO INTEGER,
	FOREIGN KEY (FK_DINOSSAURO) REFERENCES DINOSSAUROS (ID),
	FOREIGN KEY (FK_REGIAO) REFERENCES REGIOES (ID)

)

SELECT * FROM GRUPOS
INSERT INTO GRUPOS VALUES ('Anquilossauros');
INSERT INTO GRUPOS VALUES ('Ceratopsídeos');
INSERT INTO GRUPOS VALUES ('Estegossauros');
INSERT INTO GRUPOS VALUES ('Terápodes')

SELECT * FROM ERAS
INSERT INTO ERAS VALUES ('Triássico','251','200');
INSERT INTO ERAS VALUES ('Jurássico','200','145');
INSERT INTO ERAS VALUES ('Cretáceo','145','65');

SELECT * FROM REGIOES
INSERT INTO REGIOES VALUES ('Mongólia');
INSERT INTO REGIOES VALUES ('Canadá');
INSERT INTO REGIOES VALUES ('Tanzânia');
INSERT INTO REGIOES VALUES ('China');
INSERT INTO REGIOES VALUES ('América do Norte');
INSERT INTO REGIOES VALUES ('USA');

SELECT * FROM GRUPOS
SELECT * FROM ERAS
SELECT * FROM REGIOES

SELECT * FROM DINOSSAUROS
INSERT INTO DINOSSAUROS VALUES ('Saichania', '4', '1997', '145','66', '1','1');
INSERT INTO DINOSSAUROS VALUES ('Tricerátops', '6', '1887', '70','66', '1','2');
INSERT INTO DINOSSAUROS VALUES ('Kentrossauro', '2', '1909', '201','145', '2','3');
INSERT INTO DINOSSAUROS VALUES ('Pinacossauro', '6', '1999', '85','75', '1','1');
INSERT INTO DINOSSAUROS VALUES ('Alossauro', '3', '1877', '155','150', '2','4');
INSERT INTO DINOSSAUROS VALUES ('Torossauro', '8', '1891', '67','65', '1','2');
INSERT INTO DINOSSAUROS VALUES ('Anquilossauro', '8', '1906', '66','63', '1','1');

SELECT * FROM DINOSSAUROS
SELECT * FROM DESCOBRIDORES
INSERT INTO DESCOBRIDORES VALUES ('Maryanska','1');
INSERT INTO DESCOBRIDORES VALUES ('John Bell Hatcher','2');
INSERT INTO DESCOBRIDORES VALUES ('Cientistas Alemães','3');
INSERT INTO DESCOBRIDORES VALUES ('Museu Americano Natural','4');
INSERT INTO DESCOBRIDORES VALUES ('Othniel Charle Marsh','5');
INSERT INTO DESCOBRIDORES VALUES ('John Bell Hatcher','6');
INSERT INTO DESCOBRIDORES VALUES ('Barnum Brown','7');

SELECT * FROM REGIOES
SELECT * FROM DINOSSAUROS
SELECT * FROM REGIAO_DINO
INSERT INTO REGIAO_DINO VALUES ('1','1','1');
INSERT INTO REGIAO_DINO VALUES ('2', '2','2');
INSERT INTO REGIAO_DINO VALUES ('3', '3','3');
INSERT INTO REGIAO_DINO VALUES ('4', '4','4');
INSERT INTO REGIAO_DINO VALUES ('5', '5','5');
INSERT INTO REGIAO_DINO VALUES ('6', '6','6');
INSERT INTO REGIAO_DINO VALUES ('7', '7','5');

select * from DINOSSAUROS
inner join grupos on DINOSSAUROS.FK_GRUPOS = GRUPOS.ID
INNER JOIN ERAS ON DINOSSAUROS.FK_ERAS = ERAS.ID
ORDER BY DINOSSAUROS.NOME

CREATE PROCEDURE TESTE2
AS
SELECT NOME, YEAR(ANO_DESCOBERTA) AS ANO
FROM DINOSSAUROS

EXEC TESTE2

CREATE PROCEDURE TESTE3(@nomeGrupo AS VARCHAR(30))
AS
SELECT DINOSSAUROS.NOME, GRUPOS.NOME AS GRUPO
FROM DINOSSAUROS
INNER JOIN GRUPOS ON GRUPOS.ID = DINOSSAUROS.FK_GRUPOS
WHERE GRUPOS.NOME = @nomeGrupo

EXEC TESTE3 ANQUILOSSAUROS

CREATE PROCEDURE ALTERATONELADAS (@id as int, @pesoT as int)
as
update DINOSSAUROS set TONELADAS = @pesoT where ID = @id 

select * from DINOSSAUROS

exec ALTERATONELADAS 1, 5

-- EXERCICIO 5

create trigger validaPeriodo
on dinossauros
after insert, update
as
	declare @ano_inicioAntigo integer
    declare @ano_fimAntigo integer

	declare @ano_inicioNovo integer
    declare @ano_fimNovo integer

    select @ano_inicioNovo  = (select ANO_INICIO from inserted)
    select @ano_fimNovo  = (select ANO_FIM from inserted)

	select @ano_inicioAntigo  = (select ANO_INICIO from deleted)
    select @ano_fimAntigo  = (select ANO_FIM from deleted)

	IF(ROWCOUNT_BIG() = 0)
    return;

begin
	if(@ano_fimNovo > @ano_inicioNovo)
	begin
		raiserror('O ano de fim é maior que o ano de inicio, os dados estão incorretos', 14,1);
        rollback transaction;
	end
end
--TESTE EXERCICIO 5 - aqui da errado
INSERT INTO DINOSSAUROS VALUES ('Bagualossauro', '8', '1906', '60','66', '1','1');

--TESTE EXERCICIO 5 - aqui da certo
INSERT INTO DINOSSAUROS VALUES ('Bagualossauro', '8', '1906', '70','66', '1','1');
 --teste EXERCICIO 5 UPTADE
UPDATE DINOSSAUROS set ANO_INICIO = '';

